### ISSUE TITLE
Nombres comunes en Enciclovida que no corresponden al taxón

### ISSUE THREAD

**Issue by sfrontana** [CONABIO/enciclovida#358]
Hola @calonsot y @albertoglezba:

Me reportaron vía enciclovida la asignación errónea de los nombres comunes para la familia Scutellidae (http://enciclovida.mx/especies/129729-scutellidae) se lee "Estrella de mar" y para el género Ophioplocus (http://enciclovida.mx/especies/130059-ophioplocus) se lee "Estrella cojín".

Ya revisé en el catálogo centralizado y esa asociación de nombres comunes NO proviene del catálogo centralizado de la CONABIO y en efecto es errónea. ¿De que manera podrían quitar ese dato erróneo de nombre común, para estos taxones?, quedo al pendiente saludos Sarita Frontana

**Comment by sfrontana** [comment]
Hola @cgalindoleal y @calonsot :

La familia Scutellidae corresponde a la clase Echinoidea (y no a la Asteroidea) por lo que podría sustituirse por **Erizo de mar** y el género Ophioplocus pertenece a la clase Ophiuroidea por lo que podría sustituirse por **ofiuro**; ya que los nombres asignados erróneamente pertenecen a taxones de la clase Asteroidea. Saludos Sarita Frontana

**Comment by sfrontana** [comment]
Hola: @calonsot y @albertoglezba veo que la corrección ya fue realizada gracias, sin embargo el comentario que se emitió por el usuario aún no se ve respondido desde Enciclovida, ¿ustedes responden y cambian el estatus? pues aun está como Publico y pendiente, saludos Sarita Frontana

**Comment by sfrontana** [comment]
Hola @calonsot y @albertoglezba:
Reportaron el estos días vía enciclovida la asignación errónea de los nombres comunes, situación similiar a la que les reporté el 19 de diciembre de 2018, en esta ocasión los registros reportados son los siguientes:

1) La especie de ofiuro Ophioderma longicaudum (http://enciclovida.mx/especies/130965-ophioderma-longicaudum) se lee en nombre común "Pepino de mar negro" y esto es incorrecto pues la especie no está incluida en la clase Holoturoidea; en todo caso el nombre común debe ser: “ofiuro”.

2) El suborden Brissidina (http://enciclovida.mx/especies/129609-brissidina) se lee en nombre común "Pepino de mar berrugoso" y esto es incorrecto pues al igual que el taxón anterior, este suborden no está incluido en la clase Holoturoidea; en todo caso el nombre común debe ser: “erizos corazón”.
Ya revisé en el catálogo centralizado y esa asociación de nombres comunes NO proviene del catálogo centralizado de la CONABIO y en efecto es errónea. 

¿Podrían quitar los datos erróneos de los nombres comunes, para estos taxones?, quedo al pendiente saludos Sarita Frontana

**Comment by calonsot** [comment]
Hola Sarita,

Listo el recuento fue el siguiente:

- Se añadieron los nombres comunes "erizos corazón", "erizos biscocho", "dólar de arena" a la clase http://enciclovida.mx/especies/129577-clypeasteroida
- Quedo el nombre "erizon corazón" para http://enciclovida.mx/especies/129609-brissidina
- Se añadió el nombre "estrellas quebradizas" y quedo como principal (suena más sexy :P) para los "ofiuros" http://enciclovida.mx/especies/130965-ophioderma-longicaudum

Dejare abierto este issue para posteriores cambios de nombres comunes.

Saludos.

**Comment by sfrontana** [comment]
@calonsot, gracias ya revise los cambios y son correctos, entonces cambiaré el estatus en Enciclovida gracias. Estoy de acuerdo que se quede este Issue por si se requiere reportar algo más.
