### ISSUE TITLE
Nombre en Enciclovida que no deben visualizarse

### ISSUE THREAD

**Issue by sfrontana** [CONABIO/enciclovida#383]
Hola @calonsot y @albertoglezba , buen día:

Revisando el arreglo taxonómico (vista especialistas) del Reino Animalia con los phylum que contiene desplegados se ve el "Phylum Urochordata" (http://enciclovida.mx/especies/1-animalia) dado que este phylum ya no existe en el CAT Centralizado cuando le das click te lleva a una página que dice _"Lo sentimos, El taxón que deseas ver por el momento se encuentra en mantenimiento, si deseas más información al respecto déjanos un comentario, sugerencia o corrección "_.
Por favor, pueden realizar las acciones necesarias para que ya no aparezca el Phylum Urochordata en el arreglo, gracias y quedamos al pendiente.

**Comment by calonsot** [comment]
Hola,

Tienes razon, nos falto aplicar la condicion de "publico" en el arreglo taxonómico, bueno ya quedo, aproveche para poner los nombres en orden alfabético.

Saludos.

**Comment by sfrontana** [comment]
Gracias ya visualice los cambios y estos son correctos, saludos
