### ISSUE TITLE
Mini bug en el arbol

### ISSUE THREAD

**Issue by albertoglezba** [CONABIO/enciclovida#47]
Identificar de alguna manera si se llego al último nodo en el arbol, hacer que en lugar de signo de más (+) aparezca una bolita (o nada)

**Comment by calonso-conabio** [comment]
Ademas cuando se despliega un taxon con "+" en lugar de mostrar los que faltan, quita todos los taxones y lo vuelve a contruir (el orden deberia ser al reves)

**Comment by albertoglezba** [comment]
ya quedó
