### ISSUE TITLE
Fichas de peces

### ISSUE THREAD

**Issue by calonsot** [CONABIO/enciclovida#58]
Que las fichas de la pagina de peces http://www.biodiversidad.gob.mx/usos/alimentacion/peces/ 
las despliegue en el buscador, como fuente de CONABIO

**Comment by albertoglezba** [comment]
Ahora con el NUEVO buscador de peces, no es necesario solicitar la ficha, ya que el buscador de peces utiliza las fichas q utiliza enciclovida
